package com.shop.constant.enums;

import lombok.Getter;

@Getter
public enum ErrorCode {

    /* 1000 NOT_FOUND */
    MEMBER_NOT_FOUND(1001, "MEMBER_NOT_FOUND"),
    JOB_NOT_FOUND(1002, "JOB_NOT_FOUND"),
    COMPANY_NOT_FOUND(1003, "COMPANY_NOT_FOUND"),
    CUSTOMER_NOT_FOUND(1004, "CUSTOMER_NOT_FOUND"),
    CODE_NOT_FOUND(1006, "CODE_NOT_FOUND"),
    LTC_INFO_NOT_FOUND(1007, "LTC_INFO_NOT_FOUND"),
    NOTICE_NOT_FOUND(1008, "NOTICE_NOT_FOUND"),
    FILE_NAME_NOT_FOUND(1009, "FILE_NAME_NOT_FOUND"),
    DATE_PAIR_NOT_FOUND(1011, "DATE_PAIR_NOT_FOUND(START_OR_END_DATE)"),
    ORDER_NOT_FOUND(1014, "ORDER_NOT_FOUND"),
    PRODUCT_NOT_FOUND(1015, "PRODUCT_NOT_FOUND"),
    BILL_NOT_FOUND(1016, "BILL_NOT_FOUND"),
    CLIENT_NOT_FOUND(1017, "CLIENT_NOT_FOUND"),
    PRODUCT_DELIVERY_NOT_FOUND(1018, "PRODUCT_DELIVERY_NOT_FOUND"),

    /* 2000 NOT_MATCHED */
    PASSWORD_NOT_MATCHED(2001, "PASSWORD_NOT_MATCHED"),
    NEW_PASSWORD_NOT_MATCHED(2002, "NEW_PASSWORD_NOT_MATCHED"),
    CODE_NOT_MATCHED(2003, "CODE_NOT_MATCHED"),
    DTO_NOT_MATCHED(2004, "DTO_NOT_MATCHED"),

    /* 3000 ALREADY_EXISTS */
    MEMBER_ALREADY_EXISTS(3001, "MEMBER_ALREADY_EXISTS"),
    ID_ALREADY_EXISTS(3002, "ID_ALREADY_EXISTS"),
    RECIPIENT_ALREADY_EXISTS(3003, "RECIPIENT_ALREADY_EXISTS"),
    GENERAL_ALREADY_EXISTS(3004, "GENERAL_ALREADY_EXISTS"),

    /* 4000 AUTH */
    AUTHENTICATION_FAILED(4001, "AUTHENTICATION_FAILED"),
    AUTHENTICATION_REQUEST_COUNT_EXCEEDED(4002, "AUTHENTICATION_REQUEST_COUNT_EXCEEDED"),

    /* 5000 STATUS */
    MEMBER_STATUS_PENDING(5001, "MEMBER_STATUS_PENDING"),
    MEMBER_STATUS_WITHDRAWAL(5002, "MEMBER_STATUS_WITHDRAWAL"),
    NOTICE_STATUS_EXPIRED(5003, "NOTICE_STATUS_EXPIRED"),
    PRODUCT_STATUS_NOT_REQUEST(5004, "PRODUCT_STATUS_NOT_REQUEST"),
    PRODUCT_STATUS_NOT_IN_PROGRESS(5006, "PRODUCT_STATUS_NOT_IN_PROGRESS"),
    PRODUCT_STATUS_NOT_COMPLETE(5008, "PRODUCT_STATUS_NOT_COMPLETE"),
    PRODUCT_STATUS_COMPLETE(5009, "PRODUCT_STATUS_COMPLETE"),
    PRODUCT_STATUS_INVALID(5010, "PRODUCT_STATUS_INVALID"),
    QUANTITY_EXCEEDED(5011, "QUANTITY_EXCEEDED"),
    QUANTITY_ZERO(5012, "QUANTITY_ZERO"),
    PURCHASER_STATUS_NOT_RECIPIENT(5013, "PURCHASER_STATUS_NOT_RECIPIENT"),
    CUSTOMER_TYPE_NOT_GENERAL(5014, "CUSTOMER_TYPE_NOT_GENERAL"),

    /* 6000 BAD_REQUEST */
    REQUEST_PARAM_CANNOT_BE_EMPTY(6001, "REQUEST_PARAM_CANNOT_BE_EMPTY"),
    REQUEST_PARAM_INVALID(6002, "REQUEST_PARAM_INVALID"),

    /* 8000 */
    SMS_SERVICE_UNAVAILABLE(8001, "SMS_SERVICE_UNAVAILABLE"),
    LTC_SERVICE_UNAVAILABLE(8002, "LTC_SERVICE_UNAVAILABLE"),
    AWS_SERVICE_UNAVAILABLE(8003, "AWS_SERVICE_UNAVAILABLE"),

    /* 9999 UNDEFINED_EXCEPTION */
    EXCEPTION(9999, "UNDEFINED_EXCEPTION");

    final int code;
    final String message;

    ErrorCode(
        int code,
        String message
    ) {
        this.code = code;
        this.message = message;
    }
}