spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 50MB

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod
